unique_ids:
  forms:
    view_imageAssets: '1720085481855416718777118.20325'
    view_imageAssets.item: '1720085692121290031685358.9673'
  modules: {}
  server_modules: {}
  assets:
    standard-page.html: KFULKW5B224HLOQ4H5X73BNTBQLC2XY3
    theme.css: 6BK2ASXMUAXIRNJQV7FQP54QT6CHYSAK
  scripts: {}
